- name: Ubuntu router
  hosts: all
  gather_facts: yes
  become: true
  become_user: root

  tasks:
    - name: Install packages
      import_role:
        name: router-setup
        tasks_from: install
      tags:
        - never
        - install

    - name: Set up host
      import_role: 
        name: router-setup
        tasks_from: setup
      tags:
        - never
        - setup

    - name: Set up iptables
      import_role:
        name: router-setup
        tasks_from: iptables
      tags:
        - never
        - iptables

    - name: Deploy configuration
      include_role: 
        name: router-setup
        tasks_from: config
      tags:
        - always
