---
- name: Ubuntu router
  hosts: all
  gather_facts: true
  become: true
  become_user: root

  tasks:
    - name: Install packages
      ansible.builtin.import_role:
        name: router-setup
        tasks_from: install
      tags:
        - never
        - install

    - name: Set up host
      ansible.builtin.import_role:
        name: router-setup
        tasks_from: setup
      tags:
        - never
        - setup

    - name: Set up iptables
      ansible.builtin.import_role:
        name: router-setup
        tasks_from: iptables
      tags:
        - never
        - iptables

    - name: Deploy configuration
      ansible.builtin.include_role:
        name: router-setup
        tasks_from: config
      tags:
        - always

# vim: ft=yaml.ansible
