- name: Ubuntu router
  hosts: all
  gather_facts: yes
  become: true
  become_user: root

  tasks:
    - name: Install packages
      include_role:
        name: router-setup
        tasks_from: install

    - name: Set up host
      include_role: 
        name: router-setup
        tasks_from: setup

    - name: Deploy configuration
      include_role: 
        name: router-setup
        tasks_from: config
      vars: 
        zones: "{{ hostvars[inventory_hostname].zones }}"

