- name: Ubuntu router
  hosts: all
  gather_facts: yes
  become: true
  become_user: root

  tasks:
    - name: router
      include_role:
        name: router-setup
      vars: 
        zones: "{{ hostvars[inventory_hostname].zones }}"

