---
# handlers file for roles/router-setup

- name: Restart isc-dhcp-server
  ansible.builtin.systemd:
    name: isc-dhcp-server
    state: restarted

- name: Restart bind9
  ansible.builtin.systemd:
    name: bind9
    state: restarted

# vim: ft=yaml.ansible
