all: 
  hosts:
    router-01:    # Router to deploy to
      wan_interface: eth0   # Interface to the larger network
      zones:                # Different zones managed by the dns server
        - 
          name: example1.com                # Zone domain
          lan_interface: eth1               # Interface for zone
          lan_ip: 10.10.10                  # Ip base of lan_interface
          dhcp_dynamic_range_bottom: 100    # Lowest value available for dynamic dhcp
          dhcp_dynamic_range_top: 199       # Highest value available for dynamic dhcp
          dns:                              # Different static ip configs
            - 
              hostname: server-01       # Server hostname
              ip: 10.10.10.2            # Server ip
              MAC: 00:00:00:00:00:01    # Server interface MAC
              cnames:                   # CNAMES for host
                - server
            - 
              hostname: server-02
              ip: 10.10.10.1
              MAC: 00:00:00:00:00:02
        - 
          name: example2.org
          lan_interface: eth2
          lan_ip: 172.44.55
          dns:
            - 
              hostname: server-01
              ip: 172.44.55.10
              MAC: 00:00:00:00:00:03
            - 
              hostname: server-02
              ip: 172.44.55.20
              MAC: 00:00:00:00:00:04
          dhcp_dynamic_range_bottom: 50
          dhcp_dynamic_range_top: 99
