---
- name: Freeze zone
  ansible.builtin.shell: |
    rndc freeze {{ zone.name }} || true
  changed_when: true

- name: Deploy forward zone files
  ansible.builtin.template:
    src: template.hosts
    dest: "/var/lib/bind/{{ zone.name }}.hosts"
    owner: bind
    group: bind

- name: "Deploy reverse zone file {{ zone.name }}"
  ansible.builtin.template:
    src: template.rev
    dest: "/var/lib/bind/{{ '.'.join(zone.lan_ip.split('.')[::-1]) }}.rev"
    owner: bind
    group: bind
    mode: "644"

- name: Thaw zone
  ansible.builtin.shell: |
    rndc thaw {{ zone.name }}
  changed_when: true

# vim: ft=yaml.ansible
