---

- name: Prevent pop-up
  debconf: name=iptables-persistent question={{ item }} vtype=boolean value=false
  loop:
    - iptables-persistent/autosave_v4
    - iptables-persistent/autosave_v6

- name: Install packages
  apt:
    pkg:
      - iptables-persistent
      - isc-dhcp-server
      - bind9
    update_cache: yes
