---
- name: Prevent pop-up
  ansible.builtin.debconf:
    name: iptables-persistent
    question: "{{ item }}"
    vtype: boolean
    value: false
  loop:
    - iptables-persistent/autosave_v4
    - iptables-persistent/autosave_v6

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - iptables-persistent
      - isc-dhcp-server
      - bind9
    update_cache: true

- name: Proceed to set up
  ansible.builtin.import_role:
    name: router-setup
    tasks_from: setup

# vim: ft=yaml.ansible
