---
- name: Deploy netplan
  ansible.builtin.template:
    src: router.yaml.j2
    dest: /etc/netplan/router.yaml

- name: Apply netplan
  ansible.builtin.shell: |
    netplan apply
  changed_when: true

- name: Harden ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item }}"
    line: "{{ item }} no"
  loop:
    - "PermitRootLogin"
    - "PasswordAuthentication"
    - "ChallengeResponseAuthentication"
    - "UsePAM"

- name: Restart ssh
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Allow port forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Create rndc key
  ansible.builtin.command: /usr/sbin/rndc-confgen -a
  changed_when: true

- name: Use local dns
  ansible.builtin.template:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf

- name: Restart services
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: Move to iptables
  ansible.builtin.import_role:
    name: router-setup
    tasks_from: iptables

# vim: ft=yaml.ansible
