---

- name: Deploy netplan
  template:
    src: router.yaml.j2
    dest: /etc/netplan/router.yaml

- name: Apply netplan
  shell: |
    netplan apply

- name: Harden ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item }}"
    line: "{{ item }} no"
  loop:
    - "PermitRootLogin"
    - "PasswordAuthentication"
    - "ChallengeResponseAuthentication"
    - "UsePAM"

- name: Restart ssh
  service:
    name: sshd
    state: restarted

- name: Allow port forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Create rndc key
  shell:
    cmd: "/usr/sbin/rndc-confgen -a"

- name: Use local dns
  template:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf

- name: Restart services
  systemd:
    name: systemd-resolved
    state: restarted

- name: Move to iptables
  import_role:
    name: router-setup
    tasks_from: iptables

